env
  ARTIFACTS_KEY=AWS_ACCESS_KEY_ID
  ARTIFACTS_SECRET=AWS_SECRET_ACCESS_KEY
  ARTIFACTS_BUCKET=AWS_DEFAULT_BUCKET
sudo: true

language: python

services:
  - docker

install:
- pip install awscli
- $(aws ecr get-login --no-include-email)
- docker pull ${AWS_USER_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/fdb-build
matrix:
  include:
  - name: "Compile Server"    
    script:
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 3ea818c805ad6cd8f6aec2c262e0456e165ab539
      - docker run -it -v "${TRAVIS_BUILD_DIR}:/docker/foundationdb" ${AWS_USER_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/fdb-build /bin/bash -c "cd /docker/foundationdb"
addons:
  artifacts: true
    s3_region: $AWS_DEFAULT_REGION
    working_dir: $TRAVIS_BUILD_DIR/bin/*
    debug: true
<<<<<<< HEAD
=======
=======
      - docker run -it -v "${TRAVIS_BUILD_DIR}:/docker/foundationdb" ${AWS_USER_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/fdb-build /bin/bash -c "cd /docker/foundationdb && make"
  
>>>>>>> 2f44e45f31bd7c85aa50e2824db73def2797eedc
>>>>>>> 3ea818c805ad6cd8f6aec2c262e0456e165ab539
